### ISSUE TITLE
[Bug]: postgresql config file is incorrectly mapped

### ISSUE THREAD

**Issue by nitin88** [hydradatabase/hydra#130]
### What's wrong?

Docker compose file copying the local postgres configuration file to 
```      
./files/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
```

The PG instance is using different config file
```
postgres=# show config_file;
               config_file                
------------------------------------------
 /var/lib/postgresql/data/postgresql.conf
(1 row)

postgres=# 
```

Either symlink the `/var/lib/postgresql/data/postgresql.conf` to `/etc/postgresql/postgresql.conf` or fix path in PG build.

**Comment by wuputah** [comment]
😳 thanks for the bug report, fix incoming 👍
