### ISSUE TITLE
[Bug]: FYI about your name

### ISSUE THREAD

**Issue by bess** [hydradatabase/hydra#131]
### What's wrong?

Hey, looks like a great project! I just wanted to give you an FYI that I used to be part of a project called Hydra and we were forced to change our name because there is a software company in Germany with a trademark on the name Hydra in the software sphere and we were facing a legal challenge. Our project changed its name to Samvera. Just wanted to let you know so you have lots of warning in case you're ever hoping to trademark the name. 

Best wishes!

More info: https://insights.uksg.org/articles/10.1629/uksg.383

**Comment by wuputah** [comment]
thanks for the heads up, "Hydra" is, indeed, in use in many places/projects; I'll let our CEO @jhydra12 mull this over offline from here.
