### ISSUE TITLE
support pg16

### ISSUE THREAD

**Issue by wuputah** [hydradatabase/hydra#148]
### What's wrong?

pg16 is not supported :)

**Comment by stvhanna** [comment]
@wuputah Thanks for a great tool, what is the timeframe for supporting PG16? https://www.postgresql.org/about/news/postgresql-16-released-2715/

I'm spinning up a new server and would love to use the latest PG with Hydrate.

**Comment by wuputah** [comment]
Sorry, I don't have an estimate at this time.

Personally, I recommend letting new Postgres releases bake for at least 4 months (to the `.2` release, if not 7 months (to the `.3` release) before adopting it for production usage. So I would recommend continuing to use PG15 at this time.

**Comment by Vonng** [comment]
Citus 12.1 support PG 16 now ;)

**Comment by muntdan** [comment]
https://www.postgresql.org/about/news/postgresql-161-155-1410-1313-1217-and-1122-released-2749/ :)
