### ISSUE TITLE
[Bug]: Documentation bug

### ISSUE THREAD

**Issue by muntdan** [hydradatabase/hydra#163]
### What's wrong?

Documentation https://docs.hydra.so/organize/data-modeling/row-vs-column-tables states: 
`each stripe as a row of metadata that also holds up to 150,000 rows of data. Within each stripe, data is divided into chunks of 1000 rows`  but I believe it should be **10.000** rows.
As also described on the blog:  https://www.hydra.so/blog-posts/2023-03-02-columnar-updates-and-deletes
`Each stripe contains up to 15 chunks (with each chunk contains up to 10,000 rows)`

**Comment by wuputah** [comment]
thanks, fixed in https://github.com/hydradatabase/docs/commit/b2482c9e89840021a54b3254772e3b2c3869374f
