### ISSUE TITLE
support qual pushdown for varchar

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [hydradatabase/hydra#178]
### What's wrong?

Hydra columnar is fork from citus columnar. I face the problem like [issue-5562](https://github.com/citusdata/citus/issues/5562). Athough  I set the column configuration `columnar.qual_pushdown_correlation_threshold` to 0.0 (default value is 0.9), columnar chunk group filters feature is still not used if field type is VARCHAR. 
I roughly view the meta table of columnar. I think the origin reason is that `minimum_value` and `maximum_value` fields of `columnar.chunk` table are always no values (is NULL) when column field type is VARCHAR or VARCHAR(n). And when the column field type is TEXT or CHAR(n), there is a normal value in `minimum_value` and `maximum_value` fields of `columnar.chunk` table. 
Thanks for you reply! I'm a newbie trying to use hydra columnar.

**Comment by mkaruza** [comment]
Should be supported with #184 PR
