### ISSUE TITLE
[Bug]: Noticed that the locale fix in the Dockerfile is now merged with Postgres base image

### ISSUE THREAD

**Issue by kdevan** [hydradatabase/hydra#211]
### What's wrong?

https://github.com/hydradatabase/hydra/blob/24140f2f932a1b487be5212300ef0971e7e62042/Dockerfile#L6

`RUN echo en_US.UTF-8 UTF-8 >> /etc/locale.gen`

Fixed: https://github.com/docker-library/postgres/pull/1159

Was just browsing the code and noticed this small detail, thought I'd share :)

**Comment by wuputah** [comment]
thanks for letting us know! Looks like we can remove that then. I've opened #212 to do so.
