### ISSUE TITLE
[Bug]: Having index with "char"/char(1)/text column with only 1 character when used causes data falsely to not be returned

### ISSUE THREAD

**Issue by muntdan** [hydradatabase/hydra#217]
### What's wrong?

```
with CTE as ( select a,b,targetid from T1 where datetime between '2023-12-20 05:00' and '2023-12-20 06:00' )
SELECT * from CTE left join LATERAL 
(Select d,e,targetid  from T2 where (datetime > CTE .datetime - interval '1 Hour' and datetime <= CTE.datetime )
	    and targetid = CTE.targetId  
            order by DateTime desc  Limit 1) t ON true;`




The 	line:   and targetid = CTE.targetId  makes the LATERAL to not work and return nothing
Also on the CTE if you add  at the end order by datetime nothing is returned

**Comment by JerrySievert** [comment]
can you please check `SELECT current_setting('enable_memoize');`?

**Comment by muntdan** [comment]
![image](https://github.com/hydradatabase/hydra/assets/105269340/ec653043-08c5-493b-9f2d-37d7aa28e73f)

**Comment by JerrySievert** [comment]
can you provide a self-contained reproduction of the issue you are seeing?

**Comment by muntdan** [comment]
I started making some equivalent table but they also have partitions so its  bit more hard... will take a while to script all with generate series also.
In the mean time I found out that not using the CTE but another subquery makes it work.

**Comment by muntdan** [comment]
Ok so now I narrowed it down to the more where conditions that sometime cause no result:
![image](https://github.com/hydradatabase/hydra/assets/105269340/58a7ef2f-d59e-4e74-8bd0-3a37ad8b2334)
![image](https://github.com/hydradatabase/hydra/assets/105269340/425688f0-52ad-492b-be45-2df20a17f841)

**Comment by JerrySievert** [comment]
there are several issues with the `char` type in postgres, and probably shouldn't be used - are you also using it for the field type?

**Comment by muntdan** [comment]
Which field type ?

**Comment by JerrySievert** [comment]
the `char` field type, which you are doing a conversion to for comparison of `tenant`.

**Comment by muntdan** [comment]
Yes the column in db is type "char"

**Comment by muntdan** [comment]
But because when using "char" its selecting the correct partition I suspect the issue with "char" is only on Hydra
![image](https://github.com/hydradatabase/hydra/assets/105269340/f282bd8b-4004-42f5-991b-3cfd3f56b583)

**Comment by JerrySievert** [comment]
I would recommend creating tables with a different type (`TEXT`, `VARCHAR`, or whatever works other than `CHAR`) and try with that - you should not need to cast, and you should find it works a bit better.

**Comment by JerrySievert** [comment]
`CHAR` types are an issue in heap as well as columnar.  they do not work like you would expect them to, and have issues with conversions.  `tenant::text` works because it strips the additional white spaces added in the `CHAR` type that are invisible to you.

**Comment by muntdan** [comment]
I've been running Timescaledb for > 1 year with secondary dimension the same tenant "char" and had no issues so far but will surely switch on hydra where the storage is a lot smaller and regular char will not have an impact

**Comment by muntdan** [comment]
I spend all day redoing the database with tenant column as char(1) instead of "char" and surprise the bug is the same:

This 2 work:
![image](https://github.com/hydradatabase/hydra/assets/105269340/613b99f6-192e-4cef-9842-cf141be9339e)

This 2 dont work:
![image](https://github.com/hydradatabase/hydra/assets/105269340/70d154b4-12e5-49b2-b94b-a0826a14b663)

**Comment by JerrySievert** [comment]
your pictures are still showing tenant as a `char`.

**Comment by muntdan** [comment]
Yes but now is standard char(1) not the legacy "char"

**Comment by JerrySievert** [comment]
as noted, that will not fix the issue.

**Comment by muntdan** [comment]
So you reccomend only text column?

**Comment by muntdan** [comment]
So I narrowed it down to a duplicate row in event table that should not have existed due to PK constraint but still it did exist ..and thus I belive was also breaking the additional index 
> CREATE INDEX IF NOT EXISTS event_tenant_datetime_targetid_idx
    ON public.event USING btree
    (tenant ASC NULLS LAST, datetime DESC NULLS LAST, targetid ASC NULLS LAST); 
And while this broken index was in place all those query were failing.

I removed the duplicate row. I re-made the index and now is working correctly.

**Comment by muntdan** [comment]
So you believe the index causing no data return is related to vacuum?

**Comment by wuputah** [comment]
Based on the (deleted) comment history it wasn't clear that this issue was still current. If you can provide a reproducible test case we would be happy to look into it.

**Comment by muntdan** [comment]
Unfortunately all my attempts to create scripts that generate data to reproduce the issue were not successful. Only on my real db data this reproduces and I did the migration at least 7 times so is consistent.  Once I drop the index the results start coming and the excution plan no longer looks like this:
`"[
{
""Plan"": {
""Node Type"": ""Index Scan"",
""Parallel Aware"": false,
""Async Capable"": false,
""Scan Direction"": ""Forward"",
""Index Name"": ""event_ten4_2023_42_tenant_datetime_targetid_idx"",
""Relation Name"": ""event_ten4_2023_42"",
""Alias"": ""event"",
""Actual Rows"": 0,
""Actual Loops"": 1,
""Index Cond"": ""((tenant = '4'::text) AND (datetime >= '2023-10-20 04:00:00'::timestamp without time zone) AND (datetime <= '2023-10-20 08:05:00'::timestamp without time zone) AND (targetid = 44722))"",
""Rows Removed by Index Recheck"": 0
},
""Triggers"": [
]
}
]"`
