### ISSUE TITLE
[Bug]: hydra columnar  1.1 with citus 12.1 error

### ISSUE THREAD

**Issue by GPF199541** [hydradatabase/hydra#223]
### What's wrong?

waiting for server to start....2024-01-12 11:17:36.574 CST 17768     FATAL:  attempt to redefine parameter "columnar.compression"

**Comment by wuputah** [comment]
Using hydra columnar with citus is not supported.

**Comment by GPF199541** [comment]
Do you have a plan to support it？

**Comment by tunatoksoz** [comment]
Citus is a widely used extension, and i believe some people (like myself) is looking to supplement citus with hydra and do some tests together with citus. It might be a nice thing to fix.
