### ISSUE TITLE
[Bug]: Error when trying to alter table to columnar when table is case sensitive

### ISSUE THREAD

**Issue by pantonis** [hydradatabase/hydra#234]
### What's wrong?

I am trying to alter table to a columnar one and I am getting error that the relation does not exist

```SELECT columnar.alter_table_set_access_method("AccountSummary", 'columnar');```

and I get the following error:

```
ERROR:  relation "public.accountsummary" does not exist
LINE 1: SELECT  'public.accountsummary'::regclass::oid
```

It seems that the extension does not consider double quotes which denotes case sensitivity.
To reproduce it try the below:
```
CREATE TABLE "AccountSummary"
(
    id INT,
    i1 INT,
    i2 INT8,
    n NUMERIC,
    t TEXT
);
```
and then:

```
SELECT columnar.alter_table_set_access_method('"AccountSummary"', 'columnar');
```

**Comment by mkaruza** [comment]
Should be supported with #237

**Comment by pantonis** [comment]
Any estimation on when will this fix will be released?
