### ISSUE TITLE
[Bug]: Not able to convert TDE table to be accessed as columnar

### ISSUE THREAD

**Issue by shah-manthan9** [hydradatabase/hydra#241]
I'm seeking to implement transparent data encryption (TDE) to enhance the security of my Hydra database (PostgreSQL 16). I explored two potential solutions:

1. https://www.percona.com/blog/using-the-transparent-data-encryption-extension-pg_tde-with-postgresql/
2. https://www.cybertec-postgresql.com/en/products/postgresql-transparent-data-encryption/

I attempted to install and enable the Percona pg_tde extension, following the instructions provided at https://github.com/Percona-Lab/pg_tde?tab=readme-ov-file#install-from-package.

However, while I successfully added the extension to `shared_preload_libraries`, I am encountering an issue enabling it.

Error I am getting is 
```

ERROR:  extension "pg_tde" is not available
DETAIL:  Could not open extension control file "/usr/share/postgresql/16/extension/pg_tde.control": No such file or directory.
HINT:  The extension must first be installed on the system where PostgreSQL is running.
```

While checking the filesystem I can see that control files are getting generated at different location and it `/root/share/postgresql/16/extension/pg_tde.control`

After copying files in setup directory I could enable TDE and create table that is TDE enabled but can not change the access method to columnar

`Cannot convert table: table public.sbtest1 is not heap or colummnar`

**Comment by JerrySievert** [comment]
pg_tde and hydra columnar both use the same tableam functionality, and thus only one can be used per table (they cannot "stack").

the cybertec tde appears to be an abandoned fork of postgres (last updated for 12.3).

you might have better luck with full disk encryption in the kernel, but pg_tde will definitely not work in conjunction with columnar.

**Comment by wuputah** [comment]
As Jerry mentioned, tde uses tableam so there's no prospect of using both simultaneously. 

You can copy data from TDE to Hydra Columnar using:

```CREATE TABLE new_table (LIKE source_table) USING columnar;
INSERT INTO new_table SELECT * FROM source_table;```
