### ISSUE TITLE
Why calculate columnar index scan cost when disabling it?

### ISSUE THREAD

**Issue by japinli** [hydradatabase/hydra#262]
### What's wrong?

Hi,

When I see the [`CostColumnarIndexPath()`](https://github.com/hydradatabase/hydra/blob/2c2630c48b5c703e8df114dedafdd8c06ab47855/columnar/src/backend/columnar/columnar_customscan.c#L621) code, it seems that the cost of the columnar index scan is calculated when `columnar.enable_columnar_index_scan` is disabled.

**Comment by wuputah** [comment]
@mkaruza it seems like this boolean check should be flipped

**Comment by mkaruza** [comment]
IndexScan  is always calculated when `enable_indexscan` is true. This is postgres GUC variable. Columnar variable GUC is `columnar_index_scan`. Previously columnar was adding *extra cost* for IndexScan path - basically pushing this path to be less favorable than `SeqScan`.
With this index scan feature, if user know what he is doing, we *don't* want to add *extra cost* to this path so it can be more favorable. So logic, when `columnar_index_scan` is enabled this extra cost calculatioj will be skipped.

**Comment by japinli** [comment]
@mkaruza Thank you for the explanation.
