### ISSUE TITLE
convert to columnar table does not support case-sensitive table names

### ISSUE THREAD

**Issue by pantonis** [hydradatabase/hydra#264]
### What's wrong?

when we run this

SELECT columnar.alter_table_set_access_method('dw."AccountSummaryFact"', 'columnar');

we can see that table is not converted to columnar

**Comment by wuputah** [comment]
the referenced fix is in 1.1.2, see #237.

**Comment by pantonis** [comment]
Yes I have checked the code as well. and saw that change. But still doesnt work even with your suggestion above

```SELECT columnar.alter_table_set_access_method('dw.AccountSummaryFact', 'columnar');```

**Comment by wuputah** [comment]
can you show me the output from
```sql
select * from pg_available_extensions where name = 'columnar';
```

**Comment by pantonis** [comment]
````columnar	11.1-11	11.1-11	Hydra Columnar extension````

**Comment by wuputah** [comment]
Confirmed as follows:

```sql
create schema "FooBar";
create table "FooBar"."BazQux" (i1 integer) using heap;
select columnar.alter_table_set_access_method('FooBar.BazQux', 'columnar');
```

```
CREATE SCHEMA
CREATE TABLE
WARNING:  Table foobar.bazqux does not exist.
 alter_table_set_access_method
-------------------------------
 f
(1 row)
```

**Comment by pantonis** [comment]
what is the release date for 11.1-12?

**Comment by mkaruza** [comment]
Just to comment for future references. When schema and/or table should be case sensitive function argument should be provided like:

`select columnar.alter_table_set_access_method('"FooBar"."BazQux"', 'columnar');`

**Comment by pantonis** [comment]
This is what we expected actually but it didnt work. Can you please provide an estimate for release?

**Comment by mkaruza** [comment]
@wuputah Can you give estimate ?

**Comment by wuputah** [comment]
Unless you're running on Hydra Cloud, there is no need to wait for a release. You can [copy-paste the updated function](https://github.com/hydradatabase/hydra/blob/main/columnar/src/backend/columnar/sql/udfs/alter_table_set_access_method/latest.sql) to your own instance to apply the fix. This won't break future upgrades, as when the update is applied later, it will just replace it again, which will have no effect. 

If you need this fix on your instance of Hydra Cloud, please [contact support](https://dashboard.hydra.so/support).
