### ISSUE TITLE
ClickHouse comparison

### ISSUE THREAD

**Issue by ricklamers** [hydradatabase/hydra#38]
Hydra looks super interesting! Could you compare and contrast with ClickHouse? Couldn't find anything on the website or docs about it.

**Comment by wuputah** [comment]
We will be announcing some benchmarks this week. You can also have a preview by looking at the PR we just sent to ClickBench.
https://github.com/ClickHouse/ClickBench/pull/64

We have a lot more we plan to do, so this is just the beginning!

Clickhouse is designed for pure OLAP and excels at single-table performance, which is what ClickBench exercises. Hydra is targeting a more generalized data warehouse use case. So, it depends on your use case which data store is best.

**Comment by wuputah** [comment]
We are now merged in, so you can click around on https://benchmark.clickhouse.com/. We also have a new site live at https://hydra.so/ and vastly expanded docs at https://docs.hydras.io/, and [a blog post all about the new build and benchmarks](https://hydras.io/blog/2022-12-13-how-we-built-fastest-postgres-db-for-analytics).

Still need to add the benchmarks to the docs, though. 👍

**Comment by wuputah** [comment]
implemented in #116, and the work that supported creating that doc.
