### ISSUE TITLE
Trusted Language Extensions for PostgreSQL

### ISSUE THREAD

**Issue by moltar** [hydradatabase/hydra#42]
Would it ever be possible to design/develop Hydra using TLE?

This would open up the RDS use case.

I know this is probably the opposite of what, Hydra, as a company wants.

But figured I'd try to start this discussion, just in case it would be possible.

Also, not sure of the technicals behind all of this, I am not an extension expert. Maybe it would require a complete rewrite, or the TLE framework is too limiting and would make it entirely impossible for implement a columnar store.

Docs: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.Extensions.html

**Comment by wuputah** [comment]
Hydra Columnar is an [access method][1], and we need direct access to the filesystem and Postgres C hooks and API. From what I've read of TLE, it's not designed for an extension with this level of Postgres integration. 

[1]: https://www.postgresql.org/docs/current/tableam.html
