### ISSUE TITLE
Unable to start the docker on either Linux (Debian 11) or Windows Docker

### ISSUE THREAD

**Issue by muntdan** [hydradatabase/hydra#45]
no matter how I give the required param after docker run 26293962061a
`-e POSTGRES_PASSWORD=password` 
or 
` -e "POSTGRES_PASSWORD=password"`
or
`"-e POSTGRES_PASSWORD=password"`

This message is prompted and docker is exited
` Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.
       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html`

**Comment by diegoespinozac** [comment]
Hi,

I got the same issue and i found the solution, add the value of the variables and Port direct in the docker-composer.yml, then try again.

Best regards,
DE

![CA566D1F-C1E3-4AB1-A56D-3EF9C438547D](https://user-images.githubusercontent.com/54366934/221127056-8ff0bb93-ad22-4fc6-86f7-fcbf3f9597f6.jpeg)

**Comment by muntdan** [comment]
Thank you for the tip. Your example did not work identically for me.
I ended up with this:
`services:
  hydra:
    container_name: hidra.so
    image: 26293962061a
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
`

**Comment by muntdan** [comment]
I found the lucky command (the image id needs to be at the end):
`docker run --name hydra.so  -p 5423:5432 -e "POSTGRES_PASSWORD=password" 26293962061a`
