### ISSUE TITLE
WHERE on INTEGER column not working when SELECT includes certain custom types

### ISSUE THREAD

**Issue by muntdan** [hydradatabase/hydra#46]
If I try to use where on text/datetime or uuid columns it works, but if I do it on INTEGER column I have this error:
`ERROR:  unsupported byval length: 16
SQL state: XX000 `

I am able to make it work with a cast to text or varchar though.

**Comment by wuputah** [comment]
Hi, thanks for the report! Unfortunately I was not able to replicate. Can you provide more information about your enivronment and steps you took when you encountered this issue?

```
postgres=# create table t(a integer, b integer) using columnar;
CREATE TABLE
postgres=# insert into t select g, g % 10 from generate_series(1,300000) g;
INSERT 0 300000
postgres=# select count(1) from t where b >= 9;
 count 
-------
 30000
(1 row)
````

**Comment by muntdan** [comment]
I am using latest docker available for PG 14.
Indeed there is something specific to my table. So the conditions are like this: 
1) You need to have a postgis type of column (mine is "point")
2) Your select needs to include that column (so not only count(1) )
3) You need to make WHERE condition on a Integer column
Than the error appears. If I do the WHERE on other type of columns it works.

And another question: can you include in the image the postgis plugin to be able to activate it.
running the command `CREATE EXTENSION postgis;` gives this error:
ERROR:  could not open extension control file "/usr/share/postgresql/14/extension/postgis.control": No such file or directory
SQL state: 58P01

**Comment by wuputah** [comment]
Thanks, I was able to replicate using [`point`](https://www.postgresql.org/docs/current/datatype-geometric.html) as follows, so I believe it's about unsupported types of a particular [fixed] size.

```
=> create table t ( i integer, p point ) using columnar;
CREATE TABLE
=> insert into t values ( 1, '(1, 2)' );
INSERT 0 1
=> select i, p from t where i = 1;
ERROR:  unsupported byval length: 16
```
