### ISSUE TITLE
Is there any way to check if a table or a partition is columnar or row ?

### ISSUE THREAD

**Issue by muntdan** [hydradatabase/hydra#63]

**Comment by wuputah** [comment]
## Most common

If you are using `psql` you can use `\d+ tablename` to check the access method for a single table and `\d+` to see the access method for all tables.

## Advanced

You can also check the access method via the [pg_catalog](https://www.postgresql.org/docs/current/catalogs.html), we actually do that a bit in our code here:
https://github.com/hydradatabase/hydra/blob/main/columnar/src/backend/columnar/sql/udfs/alter_table_set_access_method/latest.sql#L58-L72

This is not the easiest to navigate, so as an example, here's a query that would return the access method for all tables in the `public` schema:

```sql
with tables as (
  select tablename, (schemaname || '.' || tablename)::regclass::oid as oid
  from pg_tables
  where schemaname = 'public'
)
select tables.tablename, pg_am.amname
from tables
inner join pg_class on tables.oid = pg_class.oid
inner join pg_am on pg_class.relam = pg_am.oid;
```

**Comment by muntdan** [comment]
This is perfect, thank you so much.
