### ISSUE TITLE
Running simple Vacuum after INSERT in a columnar table makes it give random errors

### ISSUE THREAD

**Issue by muntdan** [hydradatabase/hydra#66]
I have run a migration of 143mil rows into 1 table and 50mil rows into a second one.
After advice given on Discord about running Vacuum after each 5min batch insert for read query to work after,
I run the migration like first time with 2 parallel inserts on the 2 tables fallowed by vacuum after each insert for their respective table. 
I now encounter random errors from time to time which I did not on the first migration (I am using same docker and same tool to migrate): 
`Exception data:
    Severity: ERROR
    SqlState: XX000
    MessageText: insufficient data for reading boolean array
    File: columnar_reader.c
    Line: 1728
    Routine: DeserializeBoolArray`
or
`Exception data:
    Severity: ERROR
    SqlState: XX000
    MessageText: attempted to modify an unexpected stripe, columnar storage with id=10000000021 does not have stripe with id=1117
    File: columnar_metadata.c
    Line: 1692
    Routine: UpdateStripeMetadataRow`

Hydra docker is now only using 230MB RAM (it has 60GB available).

**Comment by mkaruza** [comment]
Fixed with #74
