### ISSUE TITLE
Add vectorization of aggregates

### ISSUE THREAD

**Issue by jdgriffith** [hydradatabase/hydra#73]
### What's wrong?

Awesome product you are building!

I apologize for asking this question here but I'm having trouble getting access to discord (long story).

I noticed in one of your blog posts vectorized query development started with where clauses and would eventually be implemented for other areas/functions. Has this happened yet? 

If it has been implemented, your product might be an easy drop in replacement for our current analytics platform currently based on postgres and situated in the fintech industry.

Thanks for any insight!

**Comment by wuputah** [comment]
Not yet, we have done some experimental branches but nothing committed yet.

**Comment by jdgriffith** [comment]
Thanks for the quick feedback! Best of luck on this - it's a killer feature.

**Comment by wuputah** [comment]
implemented in #143

There's undoubtedly more work to do, and we would be interested in your evaluation and feedback. Thanks!

**Comment by jdgriffith** [comment]
Incredible! Thanks for updating this and implementing the feature!
