### ISSUE TITLE
[Bug]: Parallel query uses only 1 CPU / gets long time to run

### ISSUE THREAD

**Issue by muntdan** [hydradatabase/hydra#81]
### What's wrong?

I have 2 query. If I run each one independently it takes ~ 8sec and they finish while using 8 core 100%.
If I start one and than a second one immediately, the first one finishes after 8 seconds but the second one doesn't finish after 16 seconds but after 60 seconds.
In between second 8 (after the first query finished) to second 60 the cpu usage is 1 core 100%.

First query Explain Analyze:
`"[
  {
    ""Plan"": {
      ""Node Type"": ""Aggregate"",
      ""Strategy"": ""Hashed"",
      ""Partial Mode"": ""Simple"",
      ""Parallel Aware"": false,
      ""Async Capable"": false,
      ""Actual Rows"": 5,
      ""Actual Loops"": 1,
      ""Group Key"": [""targetid""],
      ""HashAgg Batches"": 1,
      ""Peak Memory Usage"": 409,
      ""Disk Usage"": 0,
      ""Plans"": [
        {
          ""Node Type"": ""Gather"",
          ""Parent Relationship"": ""Outer"",
          ""Parallel Aware"": false,
          ""Async Capable"": false,
          ""Actual Rows"": 38088,
          ""Actual Loops"": 1,
          ""Workers Planned"": 7,
          ""Workers Launched"": 7,
          ""Single Copy"": false,
          ""Plans"": [
            {
              ""Node Type"": ""Result"",
              ""Parent Relationship"": ""Outer"",
              ""Parallel Aware"": false,
              ""Async Capable"": false,
              ""Actual Rows"": 4761,
              ""Actual Loops"": 8,
              ""Workers"": [
              ],
              ""Plans"": [
                {
                  ""Node Type"": ""Custom Scan"",
                  ""Parent Relationship"": ""Outer"",
                  ""Custom Plan Provider"": ""ColumnarScan"",
                  ""Parallel Aware"": true,
                  ""Async Capable"": false,
                  ""Relation Name"": ""trackpoint"",
                  ""Alias"": ""trackpoint"",
                  ""Actual Rows"": 4761,
                  ""Actual Loops"": 8,
                  ""Filter"": ""((speed > '0'::numeric) AND (datetime <= now()) AND (targetid = ANY ('{68162,68163,68164,68165,68166,68167,68168,68169,68170,68171,68172,68173,68174,68175,68176,68177}'::integer[])) AND (datetime >= (now() - '1 mon'::interval)))"",
                  ""Rows Removed by Filter"": 48110141,
                  ""Columnar Projected Columns"": ""datetime, targetid, speed"",
                  ""Columnar Chunk Group Filters"": ""((datetime >= (now() - '1 mon'::interval)) AND (datetime <= now()))"",
                  ""Columnar Chunk Groups Removed by Filter"": 0,
                  ""Workers"": [
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    ""Triggers"": [
    ]
  }
]"`

Second query:
`"QUERY PLAN"
"[
  {
    ""Plan"": {
      ""Node Type"": ""Aggregate"",
      ""Strategy"": ""Hashed"",
      ""Partial Mode"": ""Simple"",
      ""Parallel Aware"": false,
      ""Async Capable"": false,
      ""Actual Rows"": 3,
      ""Actual Loops"": 1,
      ""Group Key"": [""targetid""],
      ""HashAgg Batches"": 1,
      ""Peak Memory Usage"": 409,
      ""Disk Usage"": 0,
      ""Plans"": [
        {
          ""Node Type"": ""Gather"",
          ""Parent Relationship"": ""Outer"",
          ""Parallel Aware"": false,
          ""Async Capable"": false,
          ""Actual Rows"": 45531,
          ""Actual Loops"": 1,
          ""Workers Planned"": 7,
          ""Workers Launched"": 0,
          ""Single Copy"": false,
          ""Plans"": [
            {
              ""Node Type"": ""Result"",
              ""Parent Relationship"": ""Outer"",
              ""Parallel Aware"": false,
              ""Async Capable"": false,
              ""Actual Rows"": 45531,
              ""Actual Loops"": 1,
              ""Workers"": [
              ],
              ""Plans"": [
                {
                  ""Node Type"": ""Custom Scan"",
                  ""Parent Relationship"": ""Outer"",
                  ""Custom Plan Provider"": ""ColumnarScan"",
                  ""Parallel Aware"": true,
                  ""Async Capable"": false,
                  ""Relation Name"": ""trackpoint"",
                  ""Alias"": ""trackpoint"",
                  ""Actual Rows"": 45531,
                  ""Actual Loops"": 1,
                  ""Filter"": ""((mileage > '0'::double precision) AND (datetime <= now()) AND (targetid = ANY ('{72171,72172,72173,72174,72175,72176,72177,72178,72179,72180}'::integer[])) AND (datetime >= (now() - '1 mon'::interval)))"",
                  ""Rows Removed by Filter"": 384873682,
                  ""Columnar Projected Columns"": ""datetime, targetid, mileage"",
                  ""Columnar Chunk Group Filters"": ""((datetime >= (now() - '1 mon'::interval)) AND (datetime <= now()))"",
                  ""Columnar Chunk Groups Removed by Filter"": 0,
                  ""Workers"": [
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    ""Triggers"": [
    ]
  }
]"`

**Comment by muntdan** [comment]
Might be related to https://github.com/hydradatabase/hydra/issues/79

**Comment by wuputah** [comment]
The second query has "workers planned: 7, workers launched: 0" - if there are no available workers then the query will not be parallelized. I don't think there's a bug here.

**Comment by JerrySievert** [comment]
just to add, the parallel query documentation for postgres (https://www.postgresql.org/docs/10/how-parallel-query-works.html) should help you to tune your database settings specifically to deal with this issue.  it is a postgres level configuration that the columnar extension honors.

this means that even heap-based (standard postgres storage engine) queries can and will also be resource starved if you do not configure these to your own environment and database, at least wherever queries against heap storage can be parallelized.

specific parts of the documentation that might be of interest:

> The total number of background workers that can exist at any one time is limited by both [`max_worker_processes`](https://www.postgresql.org/docs/10/runtime-config-resource.html#GUC-MAX-WORKER-PROCESSES) and [`max_parallel_worker`s](https://www.postgresql.org/docs/10/runtime-config-resource.html#GUC-MAX-PARALLEL-WORKERS). Therefore, it is possible for a parallel query to run with fewer workers than planned, or even with no workers at all. The optimal plan may depend on the number of workers that are available, so this can result in poor query performance. If this occurrence is frequent, consider increasing `max_worker_processes` and `max_parallel_workers` so that more workers can be run simultaneously or alternatively reducing `max_parallel_workers_per_gather` so that the planner requests fewer workers.

**Comment by muntdan** [comment]
I agree on the principle, but again for the user experience you might consider the fallowing:
- eating all cpu available on a single query will never scale 
- 8 second duration with 8 CPU core 100% for a single query is extremely high
- timescaledb ships their container with max_parallel_workers = 16 instead of standard postgres 8
https://www.timescale.com/blog/timescale-parameters-you-should-know-about-and-tune-to-maximize-your-performance/

**Comment by wuputah** [comment]
The expectation is the docker image is a starting place - we don't know what you intend to do with it. You could be using it locally, on a small test instance, or on a larger "production" instance. We built it on top of the standard Postgres image to provide a simpler image that could more easily be customized and configured following the standard approach for the Postgres image. Recommendations on how to do that are available in the section "Database Configuration" in the [README for the standard Postgres image](https://github.com/docker-library/docs/blob/master/postgres/README.md#database-configuration).

On Hydra's hosted service, we currently set these settings depending on the instance size (and we should probably be setting more):

* work_mem
* shared_buffers
* max_parallel_workers
* max_worker_processes
* effective_cache_size

Even knowing the instance size, we cannot predict customer's intended workloads, so we will tune settings further as needed on a per-customer basis.
