### ISSUE TITLE
switch to `r/ubuntu/postgres` for base image?

### ISSUE THREAD

**Issue by wuputah** [hydradatabase/hydra#97]
currently we use https://hub.docker.com/_/postgres/ which means we are supporting a Debian base image for OSS and a Ubuntu base image for our hosted service. Switching to https://hub.docker.com/r/ubuntu/postgres would give us a more consistent base image between the two images.

I don't know how different the images are to operate and whether this would cause pain for users of the current image. We could continue to build the Debian-based image for some time (e.g. on bulleye, but not upgrade to bookworm) until we reach a deprecation date.

**Comment by owenthereal** [comment]
At the time of the writing, `ubuntu/postgres` does not have an image for pg 15 yet: https://hub.docker.com/r/ubuntu/postgres/tags

**Comment by wuputah** [comment]
good catch, I think we can't switch then!
